version: '3.9'

services:
  app-management:
    image: app-management
    container_name: app-management
    ports:
      - "8081:8081"
    restart: unless-stopped
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      directoryDatas: /app/data/
