#name: CI/CD
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Build with Maven
#        run: docker compose build
#
#      - name: connect to Docker Hub
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Tag with Docker Hub
#        run: docker tag app-management ${{ secrets.DOCKER_USERNAME }}/app-management:0.0.1
#
#      - name: Publish to Docker Hub
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/app-management:0.0.1